// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	destination "github.com/bitrise-io/go-xcode/v2/destination"
	mock "github.com/stretchr/testify/mock"
)

// Xcodebuild is an autogenerated mock type for the Xcodebuild type
type Xcodebuild struct {
	mock.Mock
}

// TestWithoutBuilding provides a mock function with given fields: xctestrun, _a1, testRepetitionMode, maximumTestRepetitions, relaunchTestsForEachRepetition, options
func (_m *Xcodebuild) TestWithoutBuilding(xctestrun string, _a1 destination.Device, testRepetitionMode string, maximumTestRepetitions int, relaunchTestsForEachRepetition bool, options ...string) (string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, xctestrun, _a1, testRepetitionMode, maximumTestRepetitions, relaunchTestsForEachRepetition)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, destination.Device, string, int, bool, ...string) string); ok {
		r0 = rf(xctestrun, _a1, testRepetitionMode, maximumTestRepetitions, relaunchTestsForEachRepetition, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, destination.Device, string, int, bool, ...string) error); ok {
		r1 = rf(xctestrun, _a1, testRepetitionMode, maximumTestRepetitions, relaunchTestsForEachRepetition, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewXcodebuild interface {
	mock.TestingT
	Cleanup(func())
}

// NewXcodebuild creates a new instance of Xcodebuild. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewXcodebuild(t mockConstructorTestingTNewXcodebuild) *Xcodebuild {
	mock := &Xcodebuild{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
